# Generated by Django 6.0.7 on 2026-07-29 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('overall', 'Overall'), ('region', 'Region'), ('product', 'Product'), ('salesperson', 'Salesperson')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='sales.product')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='sales.region')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='sales.salesperson')),
            ],
            options={
                'ordering': ['-period_start', 'target_type'],
            },
        ),
    ]
